export enum STRINGS {
  whatBuy = 'What to buy?',
  anError = 'an error occurred',
  okay = 'Okay',
  logIn = 'Log In',
  sigUp = 'Sign Up',
  createUser = 'Create a new user',
  logInInstead = 'Log in instead',
  invalidInput = 'Invalid input',
  pleaseCheck = 'Please check entered credentials!',
  authenticationFailed = 'Authentication failed!',
  pleaseCheckYourCredentials = 'Could not log you in. Please check your credentials',
  couldNotCreateUser = 'Could not create user, please check your input and try again later.',
  isRequired = 'This field is required',
  inValidEmail = 'Invalid email format',
  checkEmail = 'Please, check for correctness email',
  checkPassword = 'Please, check for correctness password',
  checkPlease = 'Please, check for correctness email or password',
  maxLengthPassword = 'The password must contain only 7 characters',
  isNumPassword = 'The password must contain only numbers',
  myMeals = 'My Meals',

}
